### ISSUE TITLE
How to process multiple classes prompt at the same time?

### ISSUE THREAD

**Issue by ByChelsea** [caoyunkang/Segment-Any-Anomaly#8]
Hi, thanks for your great work! Have you ever tried to use multiple classes prompt like 'the defect on the cable. the flaw on the cable.'? The results looks weird...

**Comment by JerryX1110** [comment]
Due to the limitation of the generation ability of the GroudingDINO model, maybe it can not support a prompt text that is very long. Thus, more trials are all you need to find a good prompt.
